### ISSUE TITLE
Check bundle delivery script versioning for README file

### ISSUE THREAD

**Issue by wkiri** [wkiri/MTE#14]
Scott said:
> readme went to 1.2, collection_document_invetory.csv still had ::1.0.

**Comment by wkiri** [comment]
I have confirmed this.  The file `pds4_bundle_template/document/collection_document_inventory.csv` has version 1.0 in it.  I am wondering if this file should be in the template.  I thought it was generated by the delivery process.  (The other inventory files do not exist in the `pds4_bundle_template/` directory but do appear in the output.)  @stevenlujpl Could you advise whether this file should be removed from the template directory?

https://github.com/wkiri/MTE/blob/master/src/pds4_bundle_template/document/collection_document_inventory.csv

**Comment by stevenlujpl** [comment]
@wkiri I am not sure why the validate tool doesn't flag this error. I tried running the validate tool with different verbosity levels (i.e., info, warn, debug), but it still doesn't flag this error. I am following up with Scott to ask for the exact command he used. 

The collection inventory files except the one for `document` collection are generated by the bundle generation script. I originally envisioned the `document` collection as a collection that contains only static information which we don't not need to change frequently, so instead of generating the `collection_document_inventory.csv` file based on the files in `document`, I hardcoded the content of the `collection_document_inventory.csv` file. 

Currently we will need to manually update the version_id fields for new deliveries. Do you think it makes sense to make the version_id field to be a template variable? This will save us time for manually updating all the version_id fields. We will just need to provide the version id from the command line interface of the bundle generation script. Please let me know what you think. Thanks.

**Comment by stevenlujpl** [comment]
@wkiri I am able to have the validate tool to flag the versioning error. We need to use the `-R pds4.bundle` option when we run the validate tool. For example, 

```
/proj/mte/pds4_validation_tool/bin/validate -R pds4.bundle ./mars_target_encyclopedia_v1.2.5/
```

**Comment by stevenlujpl** [comment]
@wkiri I updated the bundle generation script to auto-generate the inventory file for document collection.
