### ISSUE TITLE
Update jSRE model for "contains" relation using all annotated docs

### ISSUE THREAD

**Issue by wkiri** [wkiri/MTE#20]
This model will supersede the current jSRE contains model, which was trained only on LPSC 2015 documents.

**Comment by wkiri** [comment]
@youlu Please report the number of training examples with just MSL 2015 vs. with the full data set now.  Thank you!

**Comment by wkiri** [comment]
@stevenlujpl plans to compare the relations found on MER-B with the old and new Contains models.

**Comment by stevenlujpl** [comment]
@wkiri Please see the number of training examples for MSL 2015 v.s. full data set below:

| Data set | Positive examples | Negative examples | Total examples |
| -- | -- | -- | -- |
| MSL 2015 | 264 | 415 | 679 | 
| Full data set | 476 | 956 | 1432 |

**Comment by wkiri** [comment]
@stevenlujpl  I am getting a jSRE null pointer exception for one MER-A file, which processed fine in the past.  

```
Exception in thread "main" java.lang.NullPointerException
        at java.io.FileInputStream.<init>(FileInputStream.java:130)
        at org.itc.irst.tcc.sre.Predict.readParameters(Predict.java:90)
        at org.itc.irst.tcc.sre.Predict.run(Predict.java:154)
        at org.itc.irst.tcc.sre.Predict.main(Predict.java:214)
```

The lpsc_parser log file indicates:

```
[2021-11-10 11:07:35]: Processing 2004_1165.pdf
[2021-11-10 11:07:40]: /home/wkiri/Research/MTE/git/src/jsre_parser.py:168: UserWarning: jSRE output file not found, which indicates jSRE run may be failed.
  warnings.warn('jSRE output file not found, which indicates jSRE '
```

Here is the command I am running:

```Console
$ export JSON_FILE=/proj/mte/results/mer-a-jsre-v2-ads-gaz-C2HP.jsonl
$ export NER_MODEL=/proj/mte/trained_models/ner_MERA-property-salient.ser.gz
$ export GAZETTE=../../git/ref/MERA_salient_targets_minerals-2017-05_elements.gaz.txt
$ python ../../git/src/lpsc_parser.py -i /proj/mte/data/corpus-lpsc/mer-pdf/2004_1165.pdf -o $JSON_FILE -jr /proj/mte/jSRE/jsre-1.1 -n $NER_MODEL -g $GAZETTE -rt Contains HasProperty -jm /proj/mte/trained_models/jSRE-{contains-msl-mpf-phx,hasproperty-mpf-phx-reviewed-v2}.model -l mer-a-contains2-hasproperty.log
```

If I change the final command to use the previous Contains model, there is no error:
```Console
$ python ../../git/src/lpsc_parser.py -l /proj/mte/data/corpus-lpsc/mer-pdf/2004_1165.pdf -o $JSON_FILE -jr /proj/mte/jSRE/jsre-1.1 -n $NER_MODEL -g $GAZETTE -rt Contains HasProperty -jm /proj/mte/trained_models/jSRE-{lpsc15-merged-binary,hasproperty-mpf-phx-reviewed-v2}.model -l mer-a-contains2-hasproperty.log
```

I wonder what is different here.  Can you reproduce this error?  I notice that there is a left over directory `/tmp/jsre_example_30533/`, but it seems that should not conflict with my jSRE run, right?  If you remove this directory, does the problem persist?  Other ideas?

**Comment by stevenlujpl** [comment]
@wkiri I've investigated this problem. First of all, I can reproduce the error you encountered with the jSRE contains model at `/proj/mte/trained_models/jSRE-contains-msl-mpf-phx.model`. The left over directory `/tmp/jsre_example_30533/` isn't the problem. I tried using other directories to store jSRE temporary files, and the problem still persists. 

I still cannot determine the exact reason for the failure, but I suspect the jSRE model at `/proj/mte/trained_models/jSRE-contains-msl-mpf-phx.model` is corrupted somehow due to unexpected I/O problems when the model was saved to the disk. If the model is corrupted, then it should fail not only just on `2004_1165.pdf` file, but also all the other files. I am running an experiment on all 1691 documents from `/proj/mte/data/corpus-lpsc/mer-pdf/`, and so far I am seeing a lot of `NullPointerException`s. I will report more details when the run completes. 

The following Java function in `/proj/mte/jSRE/jsre-1.1/src/org/itc/irst/tcc/sre/Predict.java` caused the `NullPointerException` (specifically, the `parameter.load` line). The `File` object `paramFile` is encoded in the `model` object. I think there are two reasons that might have caused the `NullPointerException`: (1) `model.get("param")` returns a `File` object that contains a relative path from the model file to a parameter file; (2) the model file is corrupted when it was saved to disk during the training process. I conducted two experiments that ruled out reason (1). I re-trained a new jSRE contains model with the same input files from MPF, PHX, LPSC15,  and LPSC16, and I am testing the new model on all documents from `/proj/mte/data/corpus-lpsc/mer-pdf/` directory. 705 documents have been processed so far, and everything looks good. If the run with the new model completes without `NullPointerExpcetion`, I will move it to `/proj/mte/trained_models`. This new model was trained using the exact same input files and parameter settings as the model at `/proj/mte/trained_models/jSRE-contains-msl-mpf-phx.model`, and the performance numbers are also exactly the same.

```
private void readParameters(UnZipModel model) throws IOException
{
                logger.info("read parameters");

                // get the param model
                File paramFile = model.get("param");
                parameter.load(new FileInputStream(paramFile));
}
```

**Comment by stevenlujpl** [comment]
@wkiri I've copied the new jSRE contains model to the `/proj/mte/trained_models` directory:

```
/proj/mte/trained_models/jSRE-contains-msl-mpf-phx.model
```

Please let me know if you have problems using it.

**Comment by wkiri** [comment]
@youlu Thank you, I am currently running `lpsc_parser.py` on the MER-A docs with this model.  It will take a little while, but it has already processed the document that generated an error above without problems.  (As we expect :) )

**Comment by wkiri** [comment]
This process is complete.  Please see the MER-A JSON file using the new Contains model here:
`/proj/mte/results/mer-a-jsre-v2-ads-gaz-C2HP.jsonl`
and compare with content in
`/proj/mte/results/mer-a-jsre-v2-ads-gaz-CHP.jsonl`

**Comment by wkiri** [comment]
I am regenerating these outputs and will post here when they are ready.

**Comment by wkiri** [comment]
The JSON files are now available as follows:
* Old Contains model: `/proj/mte/results/mer-a-jsre-v2-ads-gaz-CHP-redo.jsonl`
* New Contains model: `/proj/mte/results/mer-a-jsre-v2-ads-gaz-C2HP-redo.jsonl`

Please share the outcome of your comparison script when you have a chance (low priority).

**Comment by wkiri** [comment]
@stevenlujpl Wow, that does not seem possible.  I have double-checked that I specified different jSRE models to each run, and the input jSRE files are quite different in size.  I will think about it some more.  Let's set this aside for now in favor of issue #9.

**Comment by wkiri** [comment]
I think we can close this issue for now.
