### ISSUE TITLE
Support HasProperty relations in `jsre_parser.py`

### ISSUE THREAD

**Issue by wkiri** [wkiri/MTE#34]

**Comment by stevenlujpl** [comment]
@wkiri I've added the support for HasProperty relations in jsre, lpsc, paper, and jgr parsers. I tested with the following 5 documents from `/proj/mte/data/corpus-lpsc/mer-a-with-targets/`, and found 2 HasProperty relations. 

```
2020_2915.pdf
2020_2929.pdf
2020_2965.pdf
2020_2975.pdf
2020_2998.pdf
```

To use these parsers, please provide the newly added argument `-rt` or `--relation_type`. The valid option for `-rt` or `--relations` is `contains` or `hasproperty`. Please see the example command that I used to process the 5 MERA documents. 

```
python ~/MTE/MTE/src/lpsc_parser.py -li mera-test.list -o mera-test.jsonl -l mera-test.log -n /proj/mte/trained_models/ner_MERA-property-salient.ser.gz -g /home/youlu/MTE/MTE/ref/MER/MERA-targets-final-salient.gaz.txt -rt hasproperty -jm /home/youlu/MTE/working_dir/jsre_example/mpf-phx-hasproperty.model
```

I also added a new argument `relation_type` to the `json2brat.py` script. This argument is used to determine the relation type (either `Contains` or `HasProperty`) to write to the ann files. The example command I used to convert jsonl to Brat ann files is shown below:

```
python ~/MTE/MTE/src/json2brat.py mera-test.jsonl out_dir hasproperty
``` 

The result .ann files can be found in the following directory if you are interested to take a look:

```
/home/youlu/MTE/working_dir/test_hasproperty/out_dir
```

Please take a look and let me know if you find any problem. Thanks.

**Comment by stevenlujpl** [comment]
Please note that these updates are currently in `issue19` branch, and they haven't been merged into the `master` branch yet.

**Comment by stevenlujpl** [comment]
@wkiri I updated the jsre parser and lpsc parser to support running multiple jSRE models, and I also added support in `json2brat.py` script to convert .jsonl to .ann file when  .jsonl has both Contains and HasProperty relations. **Please note that these updates are still in the `issue19` branch now.** My VPN was down at the time I started working on this issue and I thought I couldn't merge without VPN, but I now just realized that I could because this MTE repo is on public github. I will merge all the updates related to issue #19 and issue #34 to master once you have an opportunity to try them out.

To use lpsc parser (or jsre parse) with multiple jsre models, please see the following example command. Please note that the arguments `-rt` (or `--relation_types`) and `-jm` (or `jsre_models`) have been changed to list type arguments. 

```
python ~/MTE/MTE/src/lpsc_parser.py -li mera-test.list -o mera-test.jsonl -l mera-test.log -n /proj/mte/trained_models/ner_MERA-property-salient.ser.gz -g ~/MTE/MTE/ref/MER/MERA-targets-final-salient.gaz.txt -rt Contains HasProperty -jm /proj/mte/trained_models/jSRE-lpsc15-merged-binary.model /proj/mte/trained_models/jSRE-hasproperty-mpf-phx-reviewed-v2.model
```

The arguments of `json2brat.py` are also changed. I removed the third argument `relation_type` because we can get the relation type from the `rel` field in the jsonl file. `json2brat.py` now accepts only two arguments. The first argument is the path to the jsonl file, and the second argument is the path to the output directory. Please see the example command below:

```
python ~/MTE/MTE/src/json2brat.py mera-test.jsonl out_dir/
```

**Comment by stevenlujpl** [comment]
@wkiri Forgot to mention that I tested using the same 5 documents listed in the post above, and everything looks correct to me. Please let me know if you find any problems.

**Comment by wkiri** [comment]
@stevenlujpl This is very exciting!  I'm glad that the list types can work for the arguments.  I am eager to give this a try tomorrow.
